### PR TITLE
SSL cert generator

### LINKED ISSUE #2: Local SSL setup not complete
**Describe the bug**
The create_crt.sh script does not work and lacking documentation to create proper SSL certificates for local development

**To Reproduce**
1. In terminal run `./create_crt.sh`

**Expected behavior**
Should guide through SSL creating process and generate:

- Local CA certificate and key
- Application Certificate and key for ssl-nginx container
- Script reruns checks for existing files and does not overwrite RootCA and it's key

### PR DESCRIPTION
**Pull request by Danpiel**
Closes #2

### CODE REVIEW

**Comment by Danpiel** [comment]
Needs wrapper for macOS systems, since there readlink does not have -f switch

File: deploy/create_certificates.sh [hunk 1]
```diff
@@ -86,11 +86,11 @@ else
   # Make server key without passphrase
   echo "${yellow}Generating server key without passphrase, enter same passphrase as above${normal}"
   openssl rsa < tempkey.pem > server_key.pem
-  cat server_crt.pem scandipwa-ca.pem > server_fullchain.pem
+  cat server_key.pem scandipwa-ca.pem > server_fullchain.pem
```
Comment (alfredsgenkins) [inline deploy/create_certificates.sh]: This file never existed

**Comment by Danpiel** [comment]
@alfredsgenkins @eli-l Pushed fix, the only thing needs execute is `make cert`
